---
- hosts: all
  become: true
  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: install epel-release
    yum:
      name: epel-release
      state: latest

  - name: install git
    yum:
      name: git
      state: latest

  - name: install python34
    yum:
      name: python34
      state: latest

  - name: install python34-pip
    yum:
      name: python34-pip
      state: latest

  - name: update pip
    pip:
      name: pip
      extra_args: -U
      executable: pip3

  - name: install robotframework-lint from git repository
    pip:
      name: git+https://github.com/boakley/robotframework-lint.git
      editable: false
